# Generated by Django 5.0.4 on 2024-04-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippets',
            old_name='linennos',
            new_name='linenos',
        ),
    ]
